name: doctor_appointment_booking_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ✅ Firebase packages
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_auth_web: ^5.14.3
  cloud_firestore: ^5.6.8
  js: ^0.7.2

  # ✅ Required for formatting timestamps
  intl: ^0.18.1

  # ✅ Add this line below intl:
  shared_preferences: ^2.2.2

  # Local plugin if needed
  jitsi_meet_wrapper:
    path: packages/jitsi_meet_wrapper





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0  # ✅ Latest linting package

flutter:
  uses-material-design: true
