// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd61PQ_SkO8cw9XDOHhr42XywyOA2aT5U',
    appId: '1:774497374442:web:1ab85bd425b7044b91c793',
    messagingSenderId: '774497374442',
    projectId: 'doct-56aee',
    authDomain: 'doct-56aee.firebaseapp.com',
    storageBucket: 'doct-56aee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz0XO7rlmJdPd24QhNPXTtB5P5VCbq7c8',
    appId: '1:774497374442:android:c2feb2afdb8f503191c793',
    messagingSenderId: '774497374442',
    projectId: 'doct-56aee',
    storageBucket: 'doct-56aee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2sNbiYW3lQbXwvb4aOwmgR6GtwEDPMpw',
    appId: '1:774497374442:ios:3f60bfa7ff4a313f91c793',
    messagingSenderId: '774497374442',
    projectId: 'doct-56aee',
    storageBucket: 'doct-56aee.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2sNbiYW3lQbXwvb4aOwmgR6GtwEDPMpw',
    appId: '1:774497374442:ios:3f60bfa7ff4a313f91c793',
    messagingSenderId: '774497374442',
    projectId: 'doct-56aee',
    storageBucket: 'doct-56aee.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd61PQ_SkO8cw9XDOHhr42XywyOA2aT5U',
    appId: '1:774497374442:web:479b038ddd69c7af91c793',
    messagingSenderId: '774497374442',
    projectId: 'doct-56aee',
    authDomain: 'doct-56aee.firebaseapp.com',
    storageBucket: 'doct-56aee.firebasestorage.app',
  );
}
